name: ChatManager
main: ru.tehkode.chatmanager.bukkit.ChatManagerPlugin
depend: [ PermissionsEx ]
version: 1.19.3
author: t3hk0d3
website: www.bukkit.org
description: Chat management plugin for PermissionsEx
