name: ChatManager
main: ru.tehkode.chatmanager.bukkit.ChatManagerPlugin
depend: [ PermissionsEx ]
version: 1.13
author: t3hk0d3
website: www.bukkit.org
description: Chat management plugin from PermissionsEx
